workflow:
  rules:
    - changes:
        - server/**/*
        - .gitlab-ci.yml
    - when: never

stages:
  - test
  - build

variables:
  MARIADB_ROOT_PASSWORD: "root"
  MYSQL_DATABASE: "tam"
  DB_HOST: "mariadb"
  REDIS_HOST: "redis"
  DOCKER_DRIVER: overlay2
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"

cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - .cache/pip/

services:
  - name: mariadb:latest
    alias: mariadb
    command:
      - "--character-set-server=utf8mb4"
      - "--collation-server=utf8mb4_uca1400_as_ci"
  - name: redis:latest
    alias: redis
    command: ["redis-server", "--requirepass", "root"]

before_script:
  - apt-get update && apt-get install -y python3-pip python3-venv
  - python3 -m venv venv
  - source venv/bin/activate
  - pip install --cache-dir $PIP_CACHE_DIR pytest pytest-dependency
  - pip install --cache-dir $PIP_CACHE_DIR -r server/app/requirements.txt
  - pytest -k test_init_database

test:
  stage: test
  script:
    - cd server
    - pytest -n auto --dist=loadfile -v --junitxml=pytest-report.xml
  artifacts:
    reports:
      junit: server/pytest-report.xml

docker_build:
  stage: build
  image: docker:latest
  rules:
    - if: '$CI_COMMIT_REF_NAME == "develop"'
      changes:
        - server/app/**/*
    - when: never
  before_script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
  services:
    - name: docker:dind
  variables:
    DOCKER_HOST: tcp://docker:2376
    DOCKER_TLS_CERTDIR: "/certs"
  script:
    - docker pull $CI_REGISTRY_IMAGE:latest || true
    - docker build --build-arg BUILDKIT_INLINE_CACHE=1 --cache-from "$CI_REGISTRY_IMAGE/backend-dev:latest" -t "$CI_REGISTRY_IMAGE/backend-dev:latest" server/app/
    - docker push "$CI_REGISTRY_IMAGE/backend-dev:latest"
