version: "3.9"
services:
  mariadb:
    image: mariadb:latest
    container_name: mariadb_container
    environment:
      MARIADB_ROOT_PASSWORD : root
      MYSQL_DATABASE: tam
    command: [
      "--character-set-server=utf8mb4",
      "--collation-server=utf8mb4_uca1400_as_ci"
    ]
    ports:
      - "3306:3306"
    volumes:
      - mariadb_data:/var/lib/mysql

  python-app:
    build:
      context: ./app  
      dockerfile: Dockerfile
      args:
        PYTHON_VERSION: 3.12.8  
    container_name: python_app
    depends_on:
      - mariadb
    volumes:
      - ./app:/app
    working_dir: /app
    ports:
      - "8001:8001"
    command: ["uvicorn", "main:app", "--host=0.0.0.0", "--port=8001"]

volumes:
  mariadb_data:
