services:
  mariadb:
    image: mariadb:latest
    container_name: mariadb_container
    environment:
      MARIADB_ROOT_PASSWORD: root
      MYSQL_DATABASE: tam
    command: [ "--character-set-server=utf8mb4", "--collation-server=utf8mb4_uca1400_as_ci" ]
    ports:
      - "3306:3306"
    volumes:
      - mariadb_data:/var/lib/mysql
    healthcheck:
      test: [ "CMD", "healthcheck.sh", "--su-mysql", "--connect", "--innodb_initialized" ]
      start_period: 1m
      start_interval: 10s
      interval: 1m
      timeout: 5s
      retries: 3

  dragonfly:
    image: docker.dragonflydb.io/dragonflydb/dragonfly:latest
    container_name: dragonfly
    restart: unless-stopped
    environment:
      - DFLY_requirepass=root
      - DFLY_port=6379
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - "6379:6379"
    volumes:
      - dragonfly_data:/data
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      start_period: 1m
      start_interval: 10s
      interval: 1m
      timeout: 5s
      retries: 3

  stripe:
    image: stripe/stripe-mock:latest
    container_name: stripe
    ports:
      - "12111:12111"

  mailhog:
    image: mailhog/mailhog:latest
    container_name: mailhog
    ports:
      - "8025:8025" 
      - "1025:1025"

  backend:
    # build:
    #   context: ./app
    #   dockerfile: Dockerfile
    #   args:
    #     PYTHON_VERSION: 3.12.8
    image: registry.gitlab.com/themastercollection/theactivitymaster/backend-dev
    container_name: backend
    environment:
      - DB_HOST=mariadb
      - REDIS_HOST=dragonfly
      - STRIPE_MOCK_HOST=stripe
      - EMAIL_HOST=mailhog
      - EMAIL_PORT=1025
      - SERVER_DOMAIN=localhost:8001
      - COLUMNS=120
      - LINES=40
    depends_on:
      - mariadb
      - dragonfly
      - stripe
      - mailhog
    volumes:
      - backend_keyfiles:/app/config/keyfiles
      - backend_verifications:/app/config/verifications
    working_dir: /app
    ports:
      - "8001:8001"
    command: [ "uvicorn", "main:app", "--host=0.0.0.0", "--port=8001" ]
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8001/ping" ]
      start_period: 1m
      start_interval: 10s
      interval: 1m
      timeout: 5s
      retries: 3
    tty: true
    stdin_open: true      

volumes:
  mariadb_data:
  dragonfly_data:
  backend_keyfiles:
  backend_verifications:
