from typing import Annotated
from sqlalchemy.orm import Mapped, mapped_column, relationship
from sqlalchemy import String, Integer, ForeignKey, UniqueConstraint, UUID, Boolean, DateTime, PrimaryKeyConstraint, Enum, Text
import uuid
from datetime import datetime
import enum

from models.generic import *
from config.database import Base
from config.settings import DEFAULT_TIMEZONE

class User(Base):
    __tablename__ = "users"

    id: Mapped[Annotated[uuid.UUID, mapped_column(UUID(as_uuid=True), primary_key=True, default=uuid.uuid4)]]
    first_name: Mapped[Annotated[str, mapped_column(String(100), nullable=False)]]
    last_name: Mapped[Annotated[str, mapped_column(String(100), nullable=False)]]
    email: Mapped[Annotated[str, mapped_column(String(255), nullable=False)]]
    password: Mapped[Annotated[str, mapped_column(String(255), nullable=False)]]

    address_id: Mapped[Annotated[uuid.UUID, mapped_column(UUID(as_uuid=True), ForeignKey("addresses.id"), nullable=False)]]
    is_2fa_enabled: Mapped[Annotated[bool, mapped_column(Boolean, nullable=False, default=False)]]
    is_passkey_enabled: Mapped[Annotated[bool, mapped_column(Boolean, nullable=False, default=False)]]
    created_at: Mapped[Annotated[datetime, mapped_column(DateTime, nullable=False, default=datetime.now(DEFAULT_TIMEZONE))]]
    updated_at: Mapped[Annotated[datetime, mapped_column(DateTime, nullable=False, default=datetime.now(DEFAULT_TIMEZONE), onupdate=datetime.now(DEFAULT_TIMEZONE))]]

    address = relationship("Address", back_populates="users")
    generic_roles = relationship("GenericRole", secondary="user_roles", uselist=True, back_populates="users")
    club_roles = relationship("ClubRole", secondary="user_club_roles", uselist=True, back_populates="users")

class GenericRole(Base):
    __tablename__ = "generic_roles"

    id: Mapped[Annotated[int, mapped_column(Integer, primary_key=True, autoincrement=True)]]
    name: Mapped[Annotated[str, mapped_column(String(100), nullable=False)]]
    description: Mapped[Annotated[str, mapped_column(String(255), nullable=False)]]
    
    users = relationship("User", secondary="user_roles", uselist=True, back_populates="roles")

class UserRole(Base):
    __tablename__ = "user_roles"

    user_id: Mapped[Annotated[uuid.UUID, mapped_column(UUID(as_uuid=True), ForeignKey("users.id"), primary_key=True)]]
    role_id: Mapped[Annotated[int, mapped_column(Integer, ForeignKey("generic_roles.id"), primary_key=True)]]
    assigned_at: Mapped[Annotated[datetime, mapped_column(DateTime, nullable=False, default=datetime.now(DEFAULT_TIMEZONE))]]

    __table_args__ = (UniqueConstraint("user_id", "role_id", name="unique_user_role"),)

class User2FAMethods(enum.Enum):
    EMAIL = "email"
    TOTP = "totp"

class User2FA(Base):
    __tablename__ = "user_2fa"

    id: Mapped[Annotated[uuid.UUID, mapped_column(UUID(as_uuid=True), primary_key=True, default=uuid.uuid4)]]
    user_id: Mapped[Annotated[uuid.UUID, mapped_column(UUID(as_uuid=True), ForeignKey("users.id"), nullable=False)]]
    method: Mapped[Annotated[User2FAMethods, mapped_column(Enum(User2FAMethods), nullable=False)]] 
    secret: Mapped[Annotated[str, mapped_column(String(255), nullable=False)]]
    last_code: Mapped[Annotated[str, mapped_column(String(20), nullable=True)]]
    created_at: Mapped[Annotated[datetime, mapped_column(DateTime, nullable=False, default=datetime.now(DEFAULT_TIMEZONE))]]
    updated_at: Mapped[Annotated[datetime, mapped_column(DateTime, nullable=False, default=datetime.now(DEFAULT_TIMEZONE), onupdate=datetime.now(DEFAULT_TIMEZONE))]]

    user = relationship("User", back_populates="2fa")


class UserPasskey(Base):
    __tablename__ = "user_passkeys"

    id: Mapped[Annotated[uuid.UUID, mapped_column(UUID(as_uuid=True), primary_key=True, default=uuid.uuid4)]]
    user_id: Mapped[Annotated[uuid.UUID, mapped_column(UUID(as_uuid=True), ForeignKey("users.id"), nullable=False)]]
    credential_id: Mapped[Annotated[str, mapped_column(String(255), nullable=False, unique=True)]] # Generated by WebAuthn
    public_key: Mapped[Annotated[str, mapped_column(Text(1000), nullable=False)]] # Public key generated by WebAuthn
    sign_count: Mapped[Annotated[int, mapped_column(Integer, nullable=False, default=0)]] # Counter to prevent replay attacks
    device_name: Mapped[Annotated[str, mapped_column(String(100), nullable=False)]] # Name of the device
    created_at: Mapped[Annotated[datetime, mapped_column(DateTime, nullable=False, default=datetime.now(DEFAULT_TIMEZONE))]]
    updated_at: Mapped[Annotated[datetime, mapped_column(DateTime, nullable=False, default=datetime.now(DEFAULT_TIMEZONE), onupdate=datetime.now(DEFAULT_TIMEZONE))]]

    user = relationship("User", back_populates="passkeys")